### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by pankona** [int128/kubectl-socat#88]
Here's crash log

```
$ go version
go version go1.17.2 darwin/amd64
```

```
macOS BigSur バージョン11.6
```

```
$ kubectl external-forward 10080:www.example.com:80
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20428c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20428c9e
stack: frame={sp:0x7ffeefbff808, fp:0x7ffeefbff858} stack=[0x7ffeefb808a8,0x7ffeefbff910)
0x00007ffeefbff708:  0x01007ffeefbff728  0x0000000000000004
0x00007ffeefbff718:  0x000000000000001f  0x00007fff20428c9e
0x00007ffeefbff728:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff738:  0x00000000040351b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff7d8
0x00007ffeefbff748:  0x00000000053abf96  0x00007ffeefbff790
0x00007ffeefbff758:  0x0000000004035468 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000061f47e0
0x00007ffeefbff768:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff778:  0x00007ffeefbff7d8  0x00000000040351b1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff788:  0x00000000061f47e0  0x00007ffeefbff7c8
0x00007ffeefbff798:  0x00000000040353f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff7a8
0x00007ffeefbff7a8:  0x0000000004035420 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000061f47e0
0x00007ffeefbff7b8:  0x00000000040351b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff7d8
0x00007ffeefbff7c8:  0x00007ffeefbff7f8  0x00000000040351b1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff7d8:  0x00007ffeefbff7e0  0x00000000040351e0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff7e8:  0x00000000053bd4a7  0x000000000000002a
0x00007ffeefbff7f8:  0x00007ffeefbff848  0x000000000404af96 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff808: <0x00000000053bd4a7  0x00000000061f47e0
0x00007ffeefbff818:  0x00007ffeefbff888  0x0000000004027f46 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff828:  0x000000000620e648  0xffffffffffffffff
0x00007ffeefbff838:  0x000000c000209808  0x00007fff203da7c6
0x00007ffeefbff848:  0x00007ffeefbff890 !0x00007fff20428c9e
0x00007ffeefbff858: >0x00007ffeefbff890  0x0000000006120000
0x00007ffeefbff868:  0x000000000000048e  0x0000000004537005 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff878:  0x00000000040684ff <runtime.syscall+0x000000000000001f>  0x000000c000209130
0x00007ffeefbff888:  0x00007ffeefbff8d0  0x000000c000209100
0x00007ffeefbff898:  0x0000000004066370 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff8a8:  0x0000000004002300 <internal/cpu.processOptions+0x0000000000000280>  0x2300000000000020
0x00007ffeefbff8b8:  0x000000000402dc85 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x00000000062297a0
0x00007ffeefbff8c8:  0x0000000000000f28  0x000000c0000001a0
0x00007ffeefbff8d8:  0x0000000004064489 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff8e8:  0x0000000005573918  0x00000000061f47e0
0x00007ffeefbff8f8:  0x00007ffeefbff948  0x0000000004064385 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff908:  0x000000000406433d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x53bd4a7, 0x61f47e0})
	/Users/y-kanai/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20428c9e
stack: frame={sp:0x7ffeefbff808, fp:0x7ffeefbff858} stack=[0x7ffeefb808a8,0x7ffeefbff910)
0x00007ffeefbff708:  0x01007ffeefbff728  0x0000000000000004
0x00007ffeefbff718:  0x000000000000001f  0x00007fff20428c9e
0x00007ffeefbff728:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff738:  0x00000000040351b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff7d8
0x00007ffeefbff748:  0x00000000053abf96  0x00007ffeefbff790
0x00007ffeefbff758:  0x0000000004035468 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000061f47e0
0x00007ffeefbff768:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff778:  0x00007ffeefbff7d8  0x00000000040351b1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff788:  0x00000000061f47e0  0x00007ffeefbff7c8
0x00007ffeefbff798:  0x00000000040353f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff7a8
0x00007ffeefbff7a8:  0x0000000004035420 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000061f47e0
0x00007ffeefbff7b8:  0x00000000040351b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff7d8
0x00007ffeefbff7c8:  0x00007ffeefbff7f8  0x00000000040351b1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff7d8:  0x00007ffeefbff7e0  0x00000000040351e0 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff7e8:  0x00000000053bd4a7  0x000000000000002a
0x00007ffeefbff7f8:  0x00007ffeefbff848  0x000000000404af96 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff808: <0x00000000053bd4a7  0x00000000061f47e0
0x00007ffeefbff818:  0x00007ffeefbff888  0x0000000004027f46 <runtime.(*mheap).allocSpan+0x0000000000000546>
0x00007ffeefbff828:  0x000000000620e648  0xffffffffffffffff
0x00007ffeefbff838:  0x000000c000209808  0x00007fff203da7c6
0x00007ffeefbff848:  0x00007ffeefbff890 !0x00007fff20428c9e
0x00007ffeefbff858: >0x00007ffeefbff890  0x0000000006120000
0x00007ffeefbff868:  0x000000000000048e  0x0000000004537005 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff878:  0x00000000040684ff <runtime.syscall+0x000000000000001f>  0x000000c000209130
0x00007ffeefbff888:  0x00007ffeefbff8d0  0x000000c000209100
0x00007ffeefbff898:  0x0000000004066370 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001
0x00007ffeefbff8a8:  0x0000000004002300 <internal/cpu.processOptions+0x0000000000000280>  0x2300000000000020
0x00007ffeefbff8b8:  0x000000000402dc85 <runtime.mProf_Malloc.func1+0x0000000000000025>  0x00000000062297a0
0x00007ffeefbff8c8:  0x0000000000000f28  0x000000c0000001a0
0x00007ffeefbff8d8:  0x0000000004064489 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff8e8:  0x0000000005573918  0x00000000061f47e0
0x00007ffeefbff8f8:  0x00007ffeefbff948  0x0000000004064385 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff908:  0x000000000406433d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/Users/y-kanai/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x4537000, 0x0, 0x40487413, 0xc0002091c0)
	/Users/y-kanai/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000209130 sp=0xc000209110 pc=0x4062f3b
syscall.syscall(0x60, 0x30, 0x30, 0x100000006913a68)
	<autogenerated>:1 +0x26 fp=0xc000209178 sp=0xc000209130 pc=0x4068cc6
golang.org/x/sys/unix.ioctl(0x10, 0x6913a68, 0x10)
	/Users/y-kanai/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc0002091a8 sp=0xc000209178 pc=0x4536b59
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/y-kanai/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/unix/ioctl.go:73
golang.org/x/term.isTerminal(0x51a18e0)
	/Users/y-kanai/go/pkg/mod/golang.org/x/term@v0.0.0-20210220032956-6a3ed077a48d/term_unix.go:19 +0x50 fp=0xc000209218 sp=0xc0002091a8 pc=0x45370d0
golang.org/x/term.IsTerminal(...)
	/Users/y-kanai/go/pkg/mod/golang.org/x/term@v0.0.0-20210220032956-6a3ed077a48d/term.go:24
k8s.io/client-go/plugin/pkg/client/auth/exec.newAuthenticator(0x5108240, 0xc0000f6480, 0x0)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/plugin/pkg/client/auth/exec/exec.go:201 +0x2ba fp=0xc000209318 sp=0xc000209218 pc=0x455561a
k8s.io/client-go/plugin/pkg/client/auth/exec.GetAuthenticator(...)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/plugin/pkg/client/auth/exec/exec.go:165
k8s.io/client-go/rest.(*Config).TransportConfig(0xc000209540)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/rest/transport.go:106 +0x508 fp=0xc000209378 sp=0xc000209318 pc=0x4565308
k8s.io/client-go/rest.TransportFor(0xb)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/rest/transport.go:43 +0x19 fp=0xc000209390 sp=0xc000209378 pc=0x4564d39
k8s.io/client-go/rest.RESTClientFor(0xc000209540)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/rest/config.go:319 +0x74 fp=0xc000209528 sp=0xc000209390 pc=0x4559214
k8s.io/client-go/kubernetes/typed/admissionregistration/v1.NewForConfig(0x8)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/kubernetes/typed/admissionregistration/v1/admissionregistration_client.go:52 +0x6f fp=0xc000209758 sp=0xc000209528 pc=0x4ced06f
k8s.io/client-go/kubernetes.NewForConfig(0x7)
	/Users/y-kanai/go/pkg/mod/k8s.io/client-go@v0.21.0/kubernetes/clientset.go:404 +0x178 fp=0xc0002099b8 sp=0xc000209758 pc=0x4e787d8
github.com/int128/kubectl-external-forward/pkg/externalforwarder.ExternalForwarder.Do({{0x557e8c0, 0x62253d8}}, {0x55ab170, 0xc00018a000}, {0xc0004b58c0, {0xc000708180, 0x1, 0x1}, {0x5391bad, 0x7}, ...})
	/Users/y-kanai/go/pkg/mod/github.com/int128/kubectl-external-forward@v0.5.0/pkg/externalforwarder/external_forwarder.go:43 +0x85 fp=0xc000209ab0 sp=0xc0002099b8 pc=0x4e7f065
github.com/int128/kubectl-external-forward/pkg/externalforwarder.(*ExternalForwarder).Do(0xc0004ce290, {0x55ab170, 0xc00018a000}, {0xc0004b58c0, {0xc000708180, 0x1, 0x1}, {0x5391bad, 0x7}, {0x53d08c7, ...}})
	<autogenerated>:1 +0x8e fp=0xc000209b20 sp=0xc000209ab0 pc=0x4e81cee
github.com/int128/kubectl-external-forward/pkg/cmd.Cmd.runRootCmd({{0x557e8a0, 0xc0004ce290}}, {0x55ab170, 0xc00018a000}, {0xc000896000, 0x0, {0x0, 0x0}, {0x53d08c7, 0x34}}, ...)
	/Users/y-kanai/go/pkg/mod/github.com/int128/kubectl-external-forward@v0.5.0/pkg/cmd/cmd.go:106 +0x28d fp=0xc000209c08 sp=0xc000209b20 pc=0x503128d
github.com/int128/kubectl-external-forward/pkg/cmd.Cmd.newRootCmd.func1(0xc000890a00, {0xc0003f2080, 0x1, 0x1})
	/Users/y-kanai/go/pkg/mod/github.com/int128/kubectl-external-forward@v0.5.0/pkg/cmd/cmd.go:79 +0x6c fp=0xc000209c80 sp=0xc000209c08 pc=0x5030fac
github.com/spf13/cobra.(*Command).execute(0xc000890a00, {0xc00019a010, 0x1, 0x1})
	/Users/y-kanai/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e fp=0xc000209d40 sp=0xc000209c80 pc=0x4ea744e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000890a00)
	/Users/y-kanai/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad fp=0xc000209df8 sp=0xc000209d40 pc=0x4ea7aad
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/y-kanai/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/y-kanai/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/int128/kubectl-external-forward/pkg/cmd.Cmd.Run({{0x557e8a0, 0xc0004ce290}}, {0x55ab170, 0xc00018a000}, {0xc00019a000, 0x2, 0x2}, {0x53912b0, 0x6})
	/Users/y-kanai/go/pkg/mod/github.com/int128/kubectl-external-forward@v0.5.0/pkg/cmd/cmd.go:48 +0x16b fp=0xc000209f18 sp=0xc000209df8 pc=0x50308cb
main.main()
	/Users/y-kanai/go/pkg/mod/github.com/int128/kubectl-external-forward@v0.5.0/cmd/kubectl-external_forward/main.go:13 +0x99 fp=0xc000209f80 sp=0xc000209f18 pc=0x5031a99
runtime.main()
	/Users/y-kanai/go/src/runtime/proc.go:255 +0x227 fp=0xc000209fe0 sp=0xc000209f80 pc=0x4037b07
runtime.goexit()
	/Users/y-kanai/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000209fe8 sp=0xc000209fe0 pc=0x4066661

goroutine 35 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/Users/y-kanai/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x6a
created by k8s.io/klog/v2.init.0
	/Users/y-kanai/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xfb
```

**Comment by int128** [comment]
Thank you for your report. I suspect the old dependencies does not work with Go 1.17. Please try the new release [v0.5.1](https://github.com/int128/kubectl-external-forward/releases/tag/v0.5.1).
